### PR TITLE
 Movies show app

### PR DESCRIPTION
**Pull request by atatm**
- [ ] I merge finalMovieshow to dev . after that I try to PR from dev to main but I couldn't since it can't compare it. I try to figure it out but I cant since the deadline is getting close.

- [ ] I  Make change to the add comment button to work and it works.  when it submitted it display the comment at the top.
- [ ] I make test for counter comments.

- [ ] since I finish all the remaining activity and my assessment is approved I want to consider what I have done for creating the comment pop up and the add comment functionality including the testing 
- [ ] so by considering what I have meet the other project requirement I want to tolerate this one 
- [ ] https://drive.google.com/drive/folders/1k47LFNdS5ogbjn56kgRDnptABnkDpfpm
Screenshot (3)

### CODE REVIEW

**Review by t-yanick — CHANGES_REQUESTED** [review]
Hi @atatm and @ernestkorir , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow the Gitflow requirements for this project.
This is a GROUP CAPSTONE - while working, team members are supposed to give reviews to each other and merge their feature branches into the dev branch. The pull request link submittted should be opened from the dev branch into the main branch and include all the changes. See this [article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/code_review_flow_group_projects.md) for more details.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by rloterh — COMMENTED** [review]
Hi Alelign, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has incorrect gitflow/ Github flow. Kindly note that the gitflow of this project should have merge request flow **from development into main**. Your team members are supposed to give reviews to each other and merge their feature branches into the dev branch, which your submission **from dev branch into main**. Kindly view this article: [curriculum-transversal-skills](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/code_review_flow_group_projects.md) for further instructions on the same. Kindly resubmit your project for review when the above changes are implemented.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by EricMbouwe — COMMENTED** [review]
Hi @atatm, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⛔❌

You have submitted a project, that has incorrect gitflow/ GitHub flow. Kindly note that the gitflow of this project should have a PR from development into main. Kindly request another review with the changes from the dev branch.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by atatm** [comment]
Yes, the previous reviewer told me that my PR was invalid, that is Why I
said I want you to consider what I have done in the project. and at this
time there is nothing that  I can do , that is why I put what I have done
and that is why I put the video link in the PR request comment to show what
I have done and to consider my video recording assessment the one that got
approved.

**Pull request merged**
